steps:
  # Copy resume from parent directory to chatbot-backend/data
  - name: 'bash'
    args:
      - '-c'
      - |
        cp ../avikshithReddy_resume.pdf data/ || echo "Resume not found"
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:$SHORT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:latest'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'avik-portfolio-chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=$$OPENAI_API_KEY,GITHUB_TOKEN=$$GITHUB_TOKEN,GITHUB_USERNAME=avikshithreddy,ADMIN_INGEST_KEY=$$ADMIN_INGEST_KEY,CORS_ALLOW_ORIGINS=*'
    secretEnv: ['OPENAI_API_KEY', 'GITHUB_TOKEN', 'ADMIN_INGEST_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
      env: 'GITHUB_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/ADMIN_INGEST_KEY/versions/latest
      env: 'ADMIN_INGEST_KEY'

images:
  - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/avik-portfolio-chatbot:latest'

options:
  logging: CLOUD_LOGGING_ONLY
